language: python

python:
    - 3.6


# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
    - pip install coveralls

script:
    - coverage run --rcfile=.coveragerc setup.py test

after_success:
    - coveralls
